// This snippet file was generated by processing the source file:
// ./messaging-next/service-worker.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_init_in_sw_modular]
import { initializeApp } from "firebase/app"; 
import { getMessaging } from "firebase/messaging/sw";

const firebaseConfig = {
    apiKey: "AIzaSyBOaBGBji-q0c-34VFzLvpqrFfZFXYM590",
    authDomain: "app-domicilo.firebaseapp.com",
    projectId: "app-domicilo",
    storageBucket: "app-domicilo.appspot.com",
    messagingSenderId: "672990838205",
    appId: "1:672990838205:web:3addbe715765d8cc1726d4",
    measurementId: "G-7LP7XHXVGM"
  };
  
  // Initialize Firebase
  const app = initializeApp(firebaseConfig); 
  const messaging = getMessaging();

